SmartTraffic/Areas/AdminManager/Controllers/LoginAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.DAO;
using SmartTraffic.Areas.AdminManager.Models;
using SmartTraffic.Common;

namespace SmartTraffic.Areas.AdminManager.Controllers
{
    public class LoginAdminController : Controller
    {
        AdminDao dao = new AdminDao();
        // GET: AdminManager/LoginAdmin
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login(LoginModelAdmin admin)
        {
            if (ModelState.IsValid)
            {
                var result = dao.Login(admin.Email, admin.Password);
                if (result == true)
                {
                    var loginAdmin = dao.GetById(admin.Email);
                    var adminSession = new AdminLogin();
                    adminSession.Email = loginAdmin.Email;
                    adminSession.UserID = loginAdmin.ID;
                    Session["AdminSession"] = adminSession;
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Tài khoản hoặc mật khẩu chưa chính xác");
                }
            }
            return View("Index");
        }
    }
}

SmartTraffic/Areas/AdminManager/Views/LoginAdmin/Index.cshtml
@model Model.EF.Admin

@{
    ViewBag.Title = "Index";
    Layout = "";
}
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <title>Pooled Admin Panel Category Flat Bootstrap Responsive Web Template | Sign Up :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Pooled Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Bootstrap Core CSS -->
    <link href="~/Assets/admin/css/bootstrap.min.css" rel='stylesheet' type='text/css' />
    <!-- Custom CSS -->
    <link href="~/Assets/admin/css/style.css" rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="~/Assets/admin/css/morris.css" type="text/css" />
    <!-- Graph CSS -->
    <link href="~/Assets/admin/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="~/Assets/admin/css/jquery-ui.css">
    <!-- jQuery -->
    <script src="~/Assets/admin/js/jquery-2.1.4.min.js"></script>
    <!-- //jQuery -->
    <link href='//fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400' rel='stylesheet' type='text/css' />
    <link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <!-- lined-icons -->
    <link rel="stylesheet" href="~/Assets/admin/css/icon-font.min.css" type='text/css' />
    <!-- //lined-icons -->
</head>
<body>
    <div class="main-wthree">
        <div class="container">
            <div class="sin-w3-agile">
                <h2>Sign In</h2>
                @using (Html.BeginForm("Login", "LoginAdmin", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @Style = "color: white;" })
                    <div class="username">
                        <span class="username">Email:</span>
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "name" } })
                        <div class="clearfix"></div>
                    </div>
                    <div class="password-agileits">
                        <span class="username">Password:</span>
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "password", @Type = "Password" } })
                        <div class="clearfix"></div>
                    </div>

                    <div class="login-w3">
                        <input type="submit" value="Login" class="btn btn-default" />
                    </div>
                    <div class="clearfix"></div>


                }

            </div>
        </div>
    </div>
</body>
</html>